-- local parser_config = require('nvim-treesitter.parsers').get_parser_configs()
-- parser_config.perl = {
--   install_info = {
--     url = 'https://github.com/tree-sitter-perl/tree-sitter-perl',
--     revision = 'release',
--     files = { 'src/parser.c', 'src/scanner.c' },
--   }
-- }
