"--- Vundle specific ---"
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'mhinz/vim-signify'
Plugin 'vim-airline/vim-airline'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'scrooloose/nerdtree'
Plugin 'majutsushi/tagbar'
Plugin 'python-mode/python-mode'
Plugin 'vivien/vim-linux-coding-style'
Plugin 'flazz/vim-colorschemes'
Plugin 'Valloric/YouCompleteMe'

call vundle#end()
filetype plugin indent on

"--- User specific ---"
colorscheme Tomorrow-Night-Bright

set history=50
set autoindent
set number
set mouse=a
set cursorline
set showmatch
set t_Co=256
set laststatus=2

" Configs already set within editorconfig's file
"set encoding=utf8
"set expandtab
"set shiftwidth=4
"set tabstop=4
"set textwidth=80
"set formatoptions+=t
"
let python_highlight_all = 1
let g:pymode_rope = 0
let g:pymode_lint = 0
let g:pymode_syntax_all = 1

let g:linuxsty_pattern = ['/usr/src/', '/linux']

map <F2> :NERDTreeToggle<CR>
map <F3> :TagbarToggle<CR>
